# Generated by Django 6.0.3 on 2026-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('holiday', 'Праздник'), ('fast', 'Пост'), ('memorial', 'Памятная дата')], default='memorial', max_length=20)),
                ('day_hijri', models.PositiveSmallIntegerField(default=1)),
                ('month_hijri', models.PositiveSmallIntegerField(default=1)),
                ('gregorian_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HijriMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Номер от 1 до 12', unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Описание месяца')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации (пост, молитвы)')),
            ],
        ),
    ]
