# Generated by Django 6.0.3 on 2026-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('gregorian_date', models.DateField(verbose_name='Дата (Григорианская)')),
                ('event_type', models.CharField(choices=[('holiday', 'Праздник'), ('fasting', 'Пост'), ('memorial', 'Памятная дата')], default='holiday', max_length=20, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['gregorian_date'],
            },
        ),
    ]
